/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const AnunciarLazyRouteImport = createFileRoute('/anunciar')()
const IndexLazyRouteImport = createFileRoute('/')()

const AnunciarLazyRoute = AnunciarLazyRouteImport.update({
  id: '/anunciar',
  path: '/anunciar',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/anunciar.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/anunciar': typeof AnunciarLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/anunciar': typeof AnunciarLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/anunciar': typeof AnunciarLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/anunciar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/anunciar'
  id: '__root__' | '/' | '/anunciar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AnunciarLazyRoute: typeof AnunciarLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/anunciar': {
      id: '/anunciar'
      path: '/anunciar'
      fullPath: '/anunciar'
      preLoaderRoute: typeof AnunciarLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AnunciarLazyRoute: AnunciarLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
